# Generated by Django 4.2.21 on 2025-06-24 17:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('osdag', '0004_userproject_calculation_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userproject',
            unique_together={('user', 'project_name')},
        ),
    ]
